### ISSUE TITLE
Denormalization makes Collection.update() synchronous despite callback

### ISSUE THREAD

**Issue by nadeemja** [Meteor-Community-Packages/denormalize#11]
Hi,

My case: 

Documents from the Users collection has been denormalized into an authorCache field in various different other collections. If a User creates a Question, then that Question-document will have an authorCache field with the Users emails.

When I update the Users emails, all their Question-docs get updated - as expected. However, if there are thousands of docs, then this takes time. 

So, I was hoping that Users.update(selector, modifier, {upsert: true}, _callback_ ), when ran on the server, would make the update async and non-blocking. This is the expected behaviour according to Meteor docs.

But, this is not the case when using herteby:denormalize (via cult-of-coders:grapher).

Is there a way to make the Users.update() call return immediately, even when caches must be updated?

**Comment by Herteby** [comment]
I made it synchronous so that things like "recursive caching" would be simpler. It could be nice to have it be async, but to make that work I would have to make a whole new system to ensure that the caches are being updated in the right order.

I don't actually use Denormalize much for performance improvements, but for things that Grapher can't otherwise handle, like "right joins" (for example, fetch all posts written by a user with the name "Simon"). So I only make a cache when I need to do something like that. And it's not that often that names and emails are updated, so it's ok for me.
